# Generated by Django 5.2.7 on 2025-10-12 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('door', 'Подъездная дверь'), ('lift_pass', 'Лифт (пассажир)'), ('lift_gruz', 'Лифт (грузовой)'), ('kalitka1', 'Калитка №1'), ('kalitka2', 'Калитка №2'), ('kalitka3', 'Калитка №3'), ('kalitka4', 'Калитка №4'), ('parking', 'Паркинг')], max_length=32)),
                ('entrance_no', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('state', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['entrance_no', 'kind'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('entrance_no__isnull', False), ('kind__in', ['door', 'lift_pass', 'lift_gruz'])), ('kind__in', ['kalitka1', 'kalitka2', 'kalitka3', 'kalitka4', 'parking']), _connector='OR'), name='entrance_required_for_entrance_kinds'), models.CheckConstraint(condition=models.Q(models.Q(('entrance_no__isnull', True), ('kind__in', ['kalitka1', 'kalitka2', 'kalitka3', 'kalitka4', 'parking'])), ('kind__in', ['door', 'lift_pass', 'lift_gruz']), _connector='OR'), name='no_entrance_for_global_kinds')],
                'unique_together': {('kind', 'entrance_no')},
            },
        ),
    ]
