# Generated by Django 5.2.7 on 2025-10-12 23:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_device'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_number', models.PositiveIntegerField(blank=True, help_text='Блок/дом, напр. 18 или 20', null=True)),
                ('entrance_no', models.PositiveSmallIntegerField(blank=True, help_text='Подъезд 1..8', null=True)),
                ('apartment_no', models.CharField(blank=True, help_text='Номер квартиры, например 001 или 12', max_length=10)),
                ('car_number', models.CharField(blank=True, help_text='Госномер авто', max_length=32)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('is_active_resident', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resident', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль жильца',
                'verbose_name_plural': 'Профили жильцов',
            },
        ),
    ]
