# Generated by Django 5.2.7 on 2025-10-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_residentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentprofile',
            name='approval_status',
            field=models.CharField(choices=[('accepted', 'Принят'), ('not_accepted', 'Не принят')], db_index=True, default='not_accepted', help_text='Принят / Не принят', max_length=20, verbose_name='Статус модерации'),
        ),
        migrations.AddField(
            model_name='residentprofile',
            name='password_status',
            field=models.CharField(choices=[('updated', 'Обновлен'), ('not_updated', 'Не обновлен')], db_index=True, default='not_updated', help_text='Обновлен / Не обновлен', max_length=20, verbose_name='Статус пароля'),
        ),
    ]
