# Generated by Django 6.0.1 on 2026-01-22 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_residentprofile_approval_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=64, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('name', models.CharField(blank=True, max_length=128)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('resident', 'Resident')], default='resident', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='device',
            options={},
        ),
        migrations.AlterModelOptions(
            name='residentprofile',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='device',
            name='entrance_required_for_entrance_kinds',
        ),
        migrations.RemoveConstraint(
            model_name='device',
            name='no_entrance_for_global_kinds',
        ),
        migrations.RemoveField(
            model_name='residentprofile',
            name='is_active_resident',
        ),
        migrations.RemoveField(
            model_name='residentprofile',
            name='password_status',
        ),
        migrations.AlterField(
            model_name='residentprofile',
            name='apartment_no',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='residentprofile',
            name='approval_status',
            field=models.CharField(choices=[('accepted', 'Принят'), ('not_accepted', 'Не принят')], default='not_accepted', max_length=20),
        ),
        migrations.AlterField(
            model_name='residentprofile',
            name='car_number',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='residentprofile',
            name='entrance_no',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='residentprofile',
            name='house_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('entrance_no__isnull', False), ('kind__in', ['door', 'lift_pass', 'lift_gruz'])), models.Q(('entrance_no__isnull', True), ('kind__in', ['kalitka1', 'kalitka2', 'kalitka3', 'kalitka4', 'parking'])), _connector='OR'), name='device_entrance_rules'),
        ),
        migrations.AlterField(
            model_name='residentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='api.simpleuser'),
        ),
    ]
