# Generated by Django 6.0.1 on 2026-03-04 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_simpleuser_alter_device_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentprofile',
            name='has_parking',
            field=models.BooleanField(default=False),
        ),
    ]
