# Generated by Django 6.0.1 on 2026-03-04 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_residentprofile_has_parking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residentprofile',
            name='has_parking',
        ),
        migrations.AddField(
            model_name='simpleuser',
            name='has_parking',
            field=models.BooleanField(default=False),
        ),
    ]
