# Generated by Django 5.2.7 on 2026-03-04 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_residentprofile_has_parking_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartment',
            options={'ordering': ['entrance', 'id'], 'verbose_name': 'Квартира', 'verbose_name_plural': 'Квартиры'},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['entrance_no', 'kind'], 'verbose_name': 'Устройство', 'verbose_name_plural': 'Устройства'},
        ),
        migrations.AlterModelOptions(
            name='entrance',
            options={'ordering': ['house', 'number'], 'verbose_name': 'Подъезд', 'verbose_name_plural': 'Подъезды'},
        ),
        migrations.AlterModelOptions(
            name='house',
            options={'ordering': ['number'], 'verbose_name': 'Дом', 'verbose_name_plural': 'Дома'},
        ),
        migrations.AlterModelOptions(
            name='residentprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Профиль резидента', 'verbose_name_plural': 'Профили резидентов'},
        ),
        migrations.AlterModelOptions(
            name='simpleuser',
            options={'ordering': ['-created_at'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='apartment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='entrance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apartments', to='api.entrance', verbose_name='Подъезд'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='is_blocked',
            field=models.BooleanField(default=False, verbose_name='Заблокирована'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='note',
            field=models.TextField(blank=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='number',
            field=models.CharField(max_length=10, verbose_name='Номер квартиры'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='owner_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Имя владельца'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='device',
            name='entrance_no',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Номер подъезда'),
        ),
        migrations.AlterField(
            model_name='device',
            name='kind',
            field=models.CharField(choices=[('door', 'Подъездная дверь'), ('lift_pass', 'Лифт (пассажир)'), ('lift_gruz', 'Лифт (грузовой)'), ('kalitka1', 'Калитка №1'), ('kalitka2', 'Калитка №2'), ('kalitka3', 'Калитка №3'), ('kalitka4', 'Калитка №4'), ('parking', 'Паркинг')], max_length=32, verbose_name='Тип устройства'),
        ),
        migrations.AlterField(
            model_name='device',
            name='state',
            field=models.BooleanField(default=False, verbose_name='Включено'),
        ),
        migrations.AlterField(
            model_name='device',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='entrance',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrances', to='api.house', verbose_name='Дом'),
        ),
        migrations.AlterField(
            model_name='entrance',
            name='number',
            field=models.PositiveIntegerField(verbose_name='Номер подъезда'),
        ),
        migrations.AlterField(
            model_name='house',
            name='number',
            field=models.PositiveIntegerField(unique=True, verbose_name='Номер дома'),
        ),
        migrations.AlterField(
            model_name='residentprofile',
            name='apartment_no',
            field=models.CharField(blank=True, max_length=10, verbose_name='Номер квартиры'),
        ),
        migrations.AlterField(
            model_name='residentprofile',
            name='approval_status',
            field=models.CharField(choices=[('accepted', 'Принят'), ('not_accepted', 'Не принят')], default='not_accepted', max_length=20, verbose_name='Статус одобрения'),
        ),
        migrations.AlterField(
            model_name='residentprofile',
            name='car_number',
            field=models.CharField(blank=True, max_length=32, verbose_name='Номер машины'),
        ),
        migrations.AlterField(
            model_name='residentprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='residentprofile',
            name='entrance_no',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Номер подъезда'),
        ),
        migrations.AlterField(
            model_name='residentprofile',
            name='house_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер дома'),
        ),
        migrations.AlterField(
            model_name='residentprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=32, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='residentprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='residentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='api.simpleuser', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='simpleuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='simpleuser',
            name='has_parking',
            field=models.BooleanField(default=False, verbose_name='Парковка'),
        ),
        migrations.AlterField(
            model_name='simpleuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='simpleuser',
            name='login',
            field=models.CharField(max_length=64, unique=True, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='simpleuser',
            name='name',
            field=models.CharField(blank=True, max_length=128, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='simpleuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='simpleuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Админ'), ('resident', 'Резидент')], default='resident', max_length=32, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='simpleuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
    ]
